### ISSUE TITLE
Phalcon

### ISSUE THREAD

**Issue by xAgentXx** [kudo070/opencase#1]
I have already installed Phalcon and imported the datbase .sql, i edited the Config file for my mysql login but i get this when i try to go on my site:

Call to undefined function apc_fetch()

#0 /var/www/html/case/app/config/services.php(223): Phalcon\Cache\Backend\Apc->get('winners')
#1 [internal function]: Closure->{closure}()
#2 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#3 /var/www/html/case/app/config/services.php(48): Phalcon\Di->get('winners')
#4 [internal function]: Closure->{closure}()
#5 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#6 [internal function]: Phalcon\Di->get('view', NULL)
#7 [internal function]: Phalcon\Di->getShared('view')
#8 /var/www/html/case/public/index.php(40): Phalcon\Mvc\Application->handle()
#9 {main}

**Comment by kudo070** [comment]
> I have already installed Phalcon and imported the datbase .sql, i edited the Config file for my mysql login but i get this when i try to go on my site:
> 
> Call to undefined function apc_fetch()
> 
> #0 /var/www/html/case/app/config/services.php(223): Phalcon\Cache\Backend\Apc->get('winners')
> #1 [internal function]: Closure->{closure}()
> #2 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
> #3 /var/www/html/case/app/config/services.php(48): Phalcon\Di->get('winners')
> #4 [internal function]: Closure->{closure}()
> #5 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
> #6 [internal function]: Phalcon\Di->get('view', NULL)
> #7 [internal function]: Phalcon\Di->getShared('view')
> #8 /var/www/html/case/public/index.php(40): Phalcon\Mvc\Application->handle()
> #9 {main}

PHP 7:
sudo apt-get install php7.0-apcu php7.0-apcu-bc
PHP 5:
apt-get install php5-apcu

**Comment by xAgentXx** [comment]
Wow Tranks for this fast replie!

Know i get:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'csgo.games' doesn't exist


But i Imported the right .sql..
And do you can Say me how i Can Go Tod the Admin Panel, its my First Time with Phalcon..
Sorry For this english i am from Germany.

**Comment by xAgentXx** [comment]
Do you know how i can fix this?

**Comment by kudo070** [comment]
See the files in the folder with the models.
